<?php

const STATUS_OK = 200;
const STATUS_CREATED = 201;
const STATUS_DATA_FROM_CACHE = 203;
const STATUS_DATA_REMOVED = 204;
const STATUS_BAD_REQUEST = 400;
const STATUS_DATA_NOT_FOUND = 404;
const STATUS_METHOD_NOT_ALLOWED = 405;
