<?php

define('REQUEST_METHOD', $_SERVER['REQUEST_METHOD']);
define('REQUEST_URI', $_SERVER['REQUEST_URI']);
define('REQUEST_FROM_CACHE', isset($_SERVER['HTTP_CACHE_CONTROL']) && $_SERVER['HTTP_CACHE_CONTROL'] === 'public');
define('CACHE_REQUEST', $_SERVER['REQUEST_METHOD'] === 'GET');
